name: b2connect_flutter
ddescription: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.11.9+31

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # UI Packages
  flutter_fortune_wheel: ^1.2.0
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.0.9
  sms_autofill: ^2.2.0
  flutter_slidable: ^2.0.0
  #launch_review: ^3.0.1
  open_store: 0.2.4
  #google_ml_vision: ^0.0.7
  google_ml_vision:
    path: ./google_ml_vision-0.0.7
  #swipeable_card_stack: ^0.0.2
  #timeline_tile: ^2.0.0
  device_preview: ^1.1.0
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  package_info_plus: ^1.4.3+1
  #in_app_review: ^2.0.4
  #flare_flutter: ^3.0.2
  #simple_animations: ^4.0.0
  #animated_radial_menu: ^0.0.1

  #dots_indicator: ^2.0.0
  #smooth_page_indicator: ^1.0.0+2

  #flutter_onboard: ^1.0.3
  #intl_phone_number_input: ^0.7.0+2
  pin_code_text_field: ^1.8.0

  #hexcolor: ^2.0.5
  #quiver: ^3.0.1

  flutter_screenutil: 5.0.1

  #json_annotation: ^4.3.0

  jiffy: ^5.0.0

  flutter_easyloading: ^3.0.5
  cached_network_image: 3.2.1




  #flutter_html_view: ^0.5.11
  #flutter_html: ^0.8.2



  relative_scale: ^2.0.0
  #simple_fontellico_progress_dialog: ^0.2.0
  #persistent_bottom_nav_bar: ^4.0.2
  #font_awesome_flutter: ^9.2.0
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  camera: ^0.10.0+1
  percent_indicator: ^4.2.2
  google_maps_flutter: ^2.2.0
  #path: ^1.8.0
  #image: ^3.0.8
  path_provider: ^2.0.11
  #image_picker: ^0.8.1+3
  #file_picker: ^4.5.1
  intl: ^0.17.0
  flutter_masked_text: ^0.8.0
  #Animation packages
  show_up_animation: ^2.0.0
  flutter_staggered_animations:
    git:
      url: https://github.com/Tkko/flutter_staggered_animations
      ref: Flutter-3.0.0
  carousel_slider: ^4.1.1
  #bubble: ^1.2.1
  #intro_slider: ^3.0.2
  #google_fonts: ^2.1.0
  #material_dialogs: ^1.1.1
  #app version updating
  new_version: ^0.3.1
  #url
  #url_launcher: ^6.0.12
  # state Management
  get_it: ^7.2.0
  # http: ^0.13.4
  provider: ^6.0.3
  network_info_plus: ^2.1.4+1
  macadress_gen: ^0.0.4
  #device_info_plus: ^3.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  csc_picker: ^0.2.6
  #animated_check: ^1.0.5
  #simple_ocr_plugin: ^0.1.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  connectivity: ^3.0.6
  pull_to_refresh: ^2.0.0
  #expandable_text: ^2.2.0


  #flutter_widget_from_html: ^0.8.2
  #flutter_widget_from_html_core: ^0.8.2

  simple_html_css: ^4.0.0
  html2md: ^1.2.6

  number_inc_dec: ^0.8.0

  #fcm
  firebase_messaging: ^13.0.0
  firebase_analytics: ^9.3.3
  firebase_crashlytics: ^2.8.9
  #firebase_messaging: ^6.0.9
  #overlay_support: ^1.2.1
  firebase_core: ^1.21.1
  firebase_database: ^9.1.3
  flutter_local_notifications: ^9.9.1


  #zoho_chat: ^0.0.1
  #flutter_inappwebview: ^5.3.2
  salesiq_mobilisten: ^1.0.4
  google_nav_bar: ^5.0.6

  photo_view: ^0.14.0

  #html: ^0.15.0

  #search_page: ^2.0.0+1

  #zoho_chat: ^0.0.1






  #QR Code Generator
  qr_flutter: ^4.0.0
  timelines: ^0.1.0
  dotted_border: ^2.0.0+2
  audio_session: ^0.1.10
  #flutter_native_splash: ^2.2.4



dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  # simple_ocr_plugin:
  # path: ./simple_ocr_plugin-0.1.1
  # json_serializable: ^4.1.3

flutter_native_splash:
  color: "#E0457B"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon.png"
  adaptive_icon_forebackground: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.development
    - .env.production
    - assets/images/
    - assets/i18n/
    - assets/images/login_success.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
